# name: base

channels:
  - conda-forge

dependencies:
  - pip
  - numpy 
  - bitarray 
  - pytest 
  - pyyaml
  - iverilog
  - pyserial
  
  # Packages installed from PyPI
  - pip:
    - -r requirements.txt
