
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  simulation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: 3.9

      - name: Run simulation tests
        run: |
          py.test -n auto test

      - uses: actions/upload-artifact@v3
        with:
          name: simulation-reports
          path: |
            ucis-coverage.xml
            metrics.txt

  build-fw:
    runs-on:  ubuntu-latest
    container: 
      image: hdlc/conda:f4pga--xc7--a50t
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Run build
        run: |
          source /usr/local/etc/profile.d/conda.sh
          pip install -r requirements.txt
          cd fw
          f4pga -vv build --flow ./flow.json

      - uses: actions/upload-artifact@v3
        with:
          name: bitfile
          path: |
            fw/build/tdc_emu_top.bit

      - uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: |
            fw/build/pack.log
            fw/build/synth.log
            fw/build/*.rpt


  emulation:
    runs-on: self-hosted
    needs: [build-fw]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: bitfile
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          environment-file: environment.yml
          miniconda-version: "latest"

      - name: Run flash
        run: |
          openFPGALoader -b arty tdc_emu_top.bit

      - name: Run emulations tests
        run: |
          EMU=1 py.test --html=test_report.html --self-contained-html test

      - uses: actions/upload-artifact@v3
        with:
          name: emulation-reports
          path: |
            ucis-coverage.xml
            metrics.txt
            test_report.html
